allow_k8s_contexts('serverless-aks')
default_registry('acrdevops.azurecr.io')
k8s_yaml('./kubernetes-manifests/adservice.yaml')
k8s_yaml('./kubernetes-manifests/cartservice.yaml')
k8s_yaml('./kubernetes-manifests/checkoutservice.yaml')
k8s_yaml('./kubernetes-manifests/currencyservice.yaml')
k8s_yaml('./kubernetes-manifests/emailservice.yaml')
k8s_yaml('./kubernetes-manifests/frontend.yaml')
k8s_yaml('./kubernetes-manifests/loadgenerator.yaml')
k8s_yaml('./kubernetes-manifests/paymentservice.yaml')
k8s_yaml('./kubernetes-manifests/productcatalogservice.yaml')
k8s_yaml('./kubernetes-manifests/recommendationservice.yaml')
k8s_yaml('./kubernetes-manifests/redis.yaml')
k8s_yaml('./kubernetes-manifests/shippingservice.yaml')

docker_build('adservice', 'src/adservice')
docker_build('cartservice', 'src/cartservice')
docker_build('checkoutservice', 'src/checkoutservice')
docker_build('currencyservice', 'src/currencyservice')
docker_build('emailservice', 'src/emailservice')
docker_build('frontend', 'src/frontend')
docker_build('loadgenerator', 'src/loadgenerator')
docker_build('paymentservice', 'src/paymentservice')
docker_build('productcatalogservice', 'src/productcatalogservice')
docker_build('recommendationservice', 'src/recommendationservice')
docker_build('shippingservice', 'src/shippingservice')
