apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hipster-cert
spec:
  secretName: hipster-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - hipster.masteringk8s.com

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hipster-ingress 
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: hipster.masteringk8s.com
spec:
  tls:
  - hosts:
    - hipster.masteringk8s.com
    secretName: hipster-cert 
  rules:
  - host: hipster.masteringk8s.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
